### ISSUE TITLE
Fragmented coupling makes for adding tweaking laborious

### ISSUE THREAD

**Issue by tripdragon** [yarn-co/kepler#8]
Kepler now has
- Sticksheet
- Quantum Card
- BleedLayer
- path joiner
- blur effect
- Next to have offset layer

The coupling internally in distracting to debug, VERY prone to errors and overall nosey. I know I was shot down in the meeting about this, but its toxic to keep this up. Just adding another key seems to fail now.

The role of Kepler was simple, make a single SVG and object geometry at full size of data given.
You could then build modules that manipulate that data to build sticker sheets/cards and so forth. As it stands there are coupled conditionals, various vars being passed to defaults and so forth.

Kepler was at some point after the highres rewrite to become a requirement of Triforce.
Anyway, space fish.

**Comment by devinivy** [comment]
I don't know the current state of kepler since a few more people have worked on it, but as I recall the blur effect and path joiner only occurred in the compilation step after all the hard geometry computations had already been done– effectively "decoupled" from kepler's default functionality, though written within the same repo.

There should be a way to have all the functionality listed above within kepler without them being overly coupled together.  Maybe it's messy right now.  Should be fixable, I imagine.

Also, rather than triforce requiring kepler (which doesn't make sense to me, given that triforce doesn't ever generate SVGs), what do you think about writing a commonjs module that kepler and triforce share?– probably something that computes trixel geometry based upon a trixel file.

**Comment by tripdragon** [comment]
How about moving the namespace of Kepler to an app, and then build pipelines for all of the "modules" inside of Kepler, 
So:
Planet Finder: grid geometry builder  <- the part I was going to have as a Triforce require maybe
Pipelines:
- single SVG output object
- Beautifier <- path join and blur routine
- any others
- html header joiner + single SVG output

The majority of Stickersheet is outside, but bleed layer is within the compile as a conditional. Merge path is mostly clean just needs to be pipelined, QuantumCard got completely shoehorned into Compile.
No second look BleedLayer was also shoehorned in.

Theres a static font size of 400 and then later 18px

Also no test data to make sure I can test what each function is doing before I breaks stuff to fix stuff.

Grrrrrrrr

**Comment by semateos** [comment]
Done?

**Comment by tripdragon** [comment]
yes but could go for more work to handle the newer SVG and PNG alternatives, but for now yes.
